language: scala
jdk:
  - openjdk8
scala:
  - 2.12.11
  - 2.13.2

cache:
  yarn: true
  directories:
    - $HOME/.cache/
    - $HOME/.ivy2/local
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
